rgName          = "rg-intern-project-001"
vnetName        = "vnet-ip-001"
vmSize      = "Standard_D2s_v5"
vmLocation  = "East US"
vmName      = "multiTfLip"
vmUsername  = "terraformUser"
vmUserPw    = "hliseh&908KHI!!@#"
subnetName     =  "snet-ip-002"
linuxServerCount = 4
